name: Build

on:
  push:
    branches:
      - "*"
  pull_request:

env:
  GO_VERSION: '1.16'

jobs:
  test:
    name: Run go tests
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run:  go test -v ./...
  coverage:
    name: Report coverage analysis to codeclimate
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set codeclimate prefix
        run: |
          echo "CC_PREFIX=$(go list -m)" >> $GITHUB_ENV
      - name: Test and upload Coverage
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
        with:
          coverageCommand: go test -coverprofile=c.out ./...
          prefix: ${{ env.CC_PREFIX }}
