name: Test

on:
  push:
    branches:
      - "*"
  pull_request:
    types: [ opened, reopened ]

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.16.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run:  go test -v ./...
  coverage:
    name: Report coverage analysis to codeclimate
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set codeclimate prefix
        run: |
          echo "CC_PREFIX=$(go list -m)" >> $GITHUB_ENV
      - name: Test and upload Coverage
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
        with:
          coverageCommand: go test -coverprofile=c.out ./...
          prefix: ${{ env.CC_PREFIX }}
